spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pizzeria
    username: postgres
    password: postgres
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    hibernate:
      ddlAuto: update
    generateDdl: true
  session:
    storeType: jdbc
    jdbc:
      initializeSchema: always
      tableName: spring_session

security:
  basic:
    enabled: false
  enable-csrf: true
